<Project Sdk="Microsoft.NET.Sdk">

	<ItemGroup>
		<Using Include="InMemoryEmulator.BigQuery.Tests.Infrastructure" />
	</ItemGroup>

	<ItemGroup>
		<Content Include="xunit.runner.json" CopyToOutputDirectory="PreserveNewest" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.3.0" />
		<PackageReference Include="xunit.runner.visualstudio" Version="3.1.5">
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
			<PrivateAssets>all</PrivateAssets>
		</PackageReference>
		<PackageReference Include="xunit.v3" Version="3.2.2" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\InMemoryEmulator.BigQuery.Tests.Shared\InMemoryEmulator.BigQuery.Tests.Shared.csproj" />
	</ItemGroup>

</Project>
